x-default: &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: unless-stopped
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks: 
  traefik-net:
    external: true

volumes:
  emqx-data:
  emqx-log:


services:

  emqx:
    << : *default
    image: emqx:5.8
    container_name: emqx
    ports:
    - "18083:18083" # Admin UI
    - "1883:1883"
    volumes:
    - emqx-data:/opt/emqx/data
    - emqx-log:/opt/emqx/log
    - ./config/emqx.conf:/opt/emqx/etc/emqx.conf:ro
    - ./acl/bootstrap_users.csv:/opt/emqx/etc/auth-bootstrap-users.csv:ro
    - ./acl/acl.conf:/opt/emqx/etc/acl.conf:ro

    labels:
      traefik.enable: true
      traefik.docker.network: traefik-net
      traefik.http.routers.emqx.rule: Host(`dashboard.example.com`)
      traefik.http.routers.emqx.entrypoints: https
      traefik.http.routers.emqx.tls.certresolver: ssl
      traefik.http.services.emqx.loadbalancer.server.port: 18083
