node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}

dashboard {
  default_password = "dev"
  listeners {
    http.bind = 18083
  }
}

authentication = [
  {
    mechanism = password_based
    backend = built_in_database
    user_id_type = username
    bootstrap_file = "/opt/emqx/etc/auth-bootstrap-users.csv"
    bootstrap_type = plain
  }
  {
    mechanism = jwt
    use_jwks = false
    algorithm = hmac-based
    secret = "change-me-jwt-secret"
    secret_base64_encoded = false
    verify_claims {sub = "${username}"}
  }
]

authorization {
  sources = [
    {
      type = file
      path = "/opt/emqx/etc/acl.conf"
    }
  ]
  no_match = deny
  deny_action = ignore
}
