x-default: &default
  # cpus: 0.5
  # mem_limit: 500M
  restart: unless-stopped
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

volumes:
  redis_data:
  
services:
  redis:
    <<: *default
    image: 'redis:7-alpine'
    ports:
      - 127.0.0.1:6379:6379
    hostname: redis
    container_name: redis
    # Set the password with --requirepass.
    # Disable persistence with --save "" --appendonly no
    # if you don't want persistent data (for improve performance).
    command: ["redis-server", "--requirepass", "dev"]
    # command: ["redis-server", "--requirepass", "dev", "--save", "", "--appendonly", "no"]

    volumes:
      - 'redis_data:/data'

    healthcheck:
      test: ["CMD", "redis-cli", "-a", "dev", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
